### ISSUE TITLE
Lower SDK requirement to 2.14.0

### ISSUE THREAD

**Issue by carman247** [alhappler/alh_pdf_view#12]
Would it be possible to lower the required SDK environment from `">=2.15.0 <3.0.0"` to `">=2.14.0 <3.0.0`?

I work on a lot of projects and they would require many modifications if I was to upgrade Flutter just to use this package for one app.

**Comment by andreBalh** [comment]
I could to that if you can test that for me this with a project using version `2.14.0`
@carman247

**Comment by andreBalh** [comment]
You can test it by adding the following to your `pubspec.yaml`:

```
  rive:
    git:
      url: https://github.com/alhappler/alh_pdf_view.git
      ref: de1d4b42f1f1355a8c3bc1571e680966da2be016

**Comment by carman247** [comment]
@andreBalh 

Thanks that's perfect. I've tested in debug and release and both are fine

**Comment by andreBalh** [comment]
Updated version to `0.3.2` containing also min version of `2.14.0`
