### ISSUE TITLE
Please Add draggable Scroll Bar in PDF to scroll particular page fast

### ISSUE THREAD

**Issue by Ayushpanditmoto** [alhappler/alh_pdf_view#16]
https://www.youtube.com/shorts/OQL6thpOgM0

like this Scroll bar

**Comment by andreBalh** [comment]
Hello @Ayushpanditmoto 
Thank you for opening this issue.
I am not sure if the native side of this package can support this behaviour. It could be possible to implement an own solution but I think that this should be something outside this package.
I will investigate your requested feature and coming back soon.

**Comment by andreBalh** [comment]
Ok I see, I will release an update to this today, but I think this feature will only work for Android then @Ayushpanditmoto

**Comment by andreBalh** [comment]
Merged #20 
If you set `enableDefaultScrollHandle` to `true`, you have the scroll button on Android. For iOS, there is already a scrollbar.

I am closing the issue, if there is something wrong, feel free to reopen or to open a new issue
@Ayushpanditmoto
