### ISSUE TITLE
onPageChanged being called too many times

### ISSUE THREAD

**Issue by carman247** [alhappler/alh_pdf_view#17]
Seems like the `onPageChanged` is being called too many times when using the controller to animate to the next/prev page.

e.g. 

```
// Go to previous page

final currentPage = await _pdfController.getCurrentPage();
_pdfController.setPageWithAnimation(
  page: currentPage - 1,
);
```

If you log out the `onPageChanged` you'll see multiple logs, sometimes 5 or so.

**Comment by andreBalh** [comment]
That should not happen, I will investigate that problem, thank you @carman247

**Comment by shubhamsinha2009** [comment]
Yehh , setPagewithAnimation calls onPageChanged many times because Animation is actually going through pages one by one .  So use setPage in this case

**Comment by andreBalh** [comment]
Fixed this issue for android, now the callback is only called when changing the page. Also the first callback is removed, when the pdf view is loaded @carman247
