### ISSUE TITLE
Facing scrollhandle background laggy

### ISSUE THREAD

**Issue by Ayushpanditmoto** [alhappler/alh_pdf_view#21]
https://youtu.be/58pcnKFWrqE

**Comment by andreBalh** [comment]
That's weird, which device and version did you use? @Ayushpanditmoto

**Comment by test0terter0n** [comment]
@Ayushpanditmoto although in release mode?

**Comment by andreBalh** [comment]
That's great, I still thinks that this is a bit weird that it only works when adding a background color but I will close this for now. If it should make still some problems, then feel free to reopen it @Ayushpanditmoto
