### ISSUE TITLE
Link Support ??? onLinkHandle

### ISSUE THREAD

**Issue by shubhamsinha2009** [alhappler/alh_pdf_view#22]
onLinkHandle

**Comment by andreBalh** [comment]
Thank you for opening the issue @shubhamsinha2009 
Could you provide some more information. Do you wish a function that is already available natively? And is it for Android and iOS?

**Comment by shubhamsinha2009** [comment]
Tap on url links in pdf goes to the chrome

**Comment by petermalh** [comment]
@shubhamsinha2009 I implemented the callback onLinkHandle only for iOS because on Android, it didn't work.
If you override onLinkHandle , the default navigation to the browser is disabled and instead onLinkHandle will be called containing the clicked url. This feature comes with the next version 1.1.0

**Comment by mirkancal** [comment]
I've checked the changelogs but couldn't find. As of 2024, does it work on android as well?

**Comment by karvulf** [comment]
Hello @mirkancal, I don't think so because the library wasn't updated since then, so I doubt that there is a function that could support the link now.

**Comment by mirkancal** [comment]
It should be simple as:

```kotlin
class DefaultLinkHandler(private val channel: MethodChannel) : LinkHandler {
    override fun handleLinkEvent(event: LinkTapEvent) {
        // Assuming LinkTapEvent has a method to get the URL or you might need to extract it
        val url = event.link.uri // Adjust this line according to the actual method available in LinkTapEvent
        val arguments = HashMap<String, String?>()
        url?.let { arguments["url"] = it }
        channel.invokeMethod("onLinkHandle", arguments)
    }
}
```

```kotlin
              .linkHandler(DefaultLinkHandler(alhPdfViewChannel))```
