### ISSUE TITLE
defaultZoomFactor doesnt center the page on zooming

### ISSUE THREAD

**Issue by faheem4797** [alhappler/alh_pdf_view#28]
Is there a way to zoom and keep the focus on center like zooming from the center?

**Comment by andreBalh** [comment]
So I investigated your request.

**For iOS**
I don't see a good solution. Only if the user zooms manually, e. g. with a button, then it could be possible that this zoom goes to the center. But if the user uses his fingers to zoom, it won't be possible to specify the area to zoom in.

**For Android**
Same problem here. I don't see a configuration to enable a zoom to center. It could be only possible to zoom to center when using the manual zoom.

So if you desire a feature where you can manually zoom only to center, then I could add this but it wouldn't enable the problem the zoom with your fingers is not centered. 
Possibly if you implement something that detects your gestures you could try to add a callback that would zoom in or out. Also the zoom with fingers has to be disabled. What do you think? @faheem4797

**Comment by andreBalh** [comment]
Closing because of no response
