### ISSUE TITLE
PDF View has blank screen after showing up the keyboard on android

### ISSUE THREAD

**Issue by alexaung** [alhappler/alh_pdf_view#3]
I create floatingActionButton to call the AlertDialog to enter page number and return the value to setPage. Please see the code. If I don't call the dialog and hardcode the specific page number, it is working. And It is only happening in android.

    ElevatedButton(
        style: ElevatedButton.styleFrom(
        elevation: 0,
        side: const BorderSide(
        color: Colors.white,
        ),
        minimumSize: Size.zero,
        tapTargetSize: MaterialTapTargetSize.shrinkWrap,
        ),
        onPressed: () async {
            final result = await openDialog();
            if (result == null || result.isEmpty) return;
            int pageNumber = int.parse(result);
            await snapshot.data!.setPage(page: pageNumber - 1); <==== If I only call this line with hard code value, it is working.
       },
       child: Text("${currentPage! + 1}"),
    ),		

Dialog

    Future<String?> openDialog() => showDialog<String>(
        context: context,
        builder: (context) => StatefulBuilder(
          builder: (context, setState) {
            return AlertDialog(
              title: const Text('Go to page'),
              content: TextField(
                //autofocus: true,
                decoration: const InputDecoration(hintText: 'Page number'),
                keyboardType: TextInputType.number,
                inputFormatters: <TextInputFormatter>[
                  FilteringTextInputFormatter.digitsOnly
                ],
                controller: textController,
                onChanged: (value) {
                  if (value.isNotEmpty) {
                    int pageNumber = int.parse(value);
                    setState(() {
                      isButtonActive = pageNumber < pages!;
                    });
                  }
                },
                onSubmitted: (_) => gotToPage(),
              ),
              actions: [
                TextButton(
                  onPressed: () {
                    Navigator.of(context).pop();
                    
                  },
                  child: const Text('Cancel'),
                ),
                TextButton(
                  style: TextButton.styleFrom(
                      onSurface: Theme.of(context).primaryColor),
                  onPressed: isButtonActive
                      ? () {
                          gotToPage();
                          
                        }
                      : null,
                  child: const Text('Move'),
                ),
              ],
            );
          },
        ),
      );

      void gotToPage() {
        Navigator.of(context).pop(textController?.text);
        textController?.clear();
      }

Full Page Code 

    import 'dart:async';
    import 'dart:io';
    import 'package:alh_pdf_view/lib.dart';
    import 'package:flutter/foundation.dart';
    import 'package:flutter/material.dart';
    import 'package:flutter/services.dart';
    import 'package:path_provider/path_provider.dart';
    import 'package:auto_size_text/auto_size_text.dart';
    import 'package:thitsarparami/helper/enum.dart';
    import 'package:thitsarparami/widgets/circular_progress_indicator_widget.dart';

    class PdfView extends StatefulWidget {
       final String url;
       final LoadPDF loadPDF;
       final String title;
    const PdfView(
      {Key? key, required this.title, required this.url, required this.loadPDF})
      : super(key: key);

      @override
      State<PdfView> createState() => _PdfViewerState();
    }. 

    class _PdfViewerState extends State<PdfView> with WidgetsBindingObserver {
      String? path;
       bool _isLoading = true;
      TextEditingController? textController;

      final Completer<AlhPdfViewController> _controller =
      Completer<AlhPdfViewController>();
      int? pages = 0;
      int? currentPage = 0;
      bool isReady = false;
      String errorMessage = '';
       bool isButtonActive = false;

      loadDocument() async {
    String fileName = widget.url.split("/").last;
    switch (widget.loadPDF) {
      case LoadPDF.assets:
        fromAsset(widget.url, fileName).then((f) {
          setState(() {
            path = f.path;
            _isLoading = false;
          });
        });
        break;
      case LoadPDF.url:
        createFileOfPdfUrl().then((f) {
          setState(() {
            path = f.path;
            _isLoading = false;
          });
        });
        break;
      case LoadPDF.file:
        File file = File(widget.url);
        setState(() {
          path = file.path;
          _isLoading = false;
        });
        break;
    }
      }

      Future<File> createFileOfPdfUrl() async {
        Completer<File> completer = Completer();
     //print("Start download file from internet!");
        try {
      final url = widget.url;
      final filename = url.substring(url.lastIndexOf("/") + 1);
      var request = await HttpClient().getUrl(Uri.parse(url));
      var response = await request.close();
      var bytes = await consolidateHttpClientResponseBytes(response);
      var dir = await getApplicationDocumentsDirectory();
      //print("Download files");
      //print("${dir.path}/$filename");
      File file = File("${dir.path}/$filename");

          await file.writeAsBytes(bytes, flush: true);
          completer.complete(file);
         } catch (e) {
          throw Exception('Error parsing asset file!');
        }

        return completer.future;
      }

      Future<File> fromAsset(String asset, String filename) async {
    // To open from assets, you can copy them to the app storage folder, and the access them "locally"
         Completer<File> completer = Completer();

        try {
      var dir = await getApplicationDocumentsDirectory();
      File file = File("${dir.path}/$filename");
      var data = await rootBundle.load(asset);
      var bytes = data.buffer.asUint8List();
      await file.writeAsBytes(bytes, flush: true);
      completer.complete(file);
    } catch (e) {
      throw Exception('Error parsing asset file!');
    }

        return completer.future;
      }

      @override
      void initState() {
        super.initState();
        loadDocument();
        textController = TextEditingController();
       }

       @override
       void dispose() {
         textController?.dispose();
         super.dispose();
       }

       @override
       Widget build(BuildContext context) {
         return Scaffold(
          backgroundColor: Theme.of(context).backgroundColor,
       appBar: AppBar(
        centerTitle: true,
        backgroundColor: Theme.of(context).backgroundColor,
        elevation: 0,
        title: AutoSizeText(
          widget.title,
          style: Theme.of(context).appBarTheme.titleTextStyle,
        ),
        leading: IconButton(
          onPressed: () {
            Navigator.pop(context);
          },
          icon: Icon(
            Icons.arrow_back,
            color: Theme.of(context).primaryIconTheme.color!,
          ),
        ),
      ),
      body: Center(
        child: _isLoading
            ? const CircularProgressIndicatorWidget()
            : AlhPdfView(
                filePath: path,
                enableSwipe: true,
                swipeHorizontal: false,
                autoSpacing: false,
                pageFling: true,
                pageSnap: true,
                defaultPage: currentPage!,
                fitPolicy: FitPolicy.both,
                //preventLinkNavigation:false, // if set to true the link is handled in flutter
                onRender: (_pages) {
                  setState(() {
                    pages = _pages;
                    isReady = true;
                  });
                },
                onError: (error) {
                  setState(() {
                    errorMessage = error.toString();
                  });
                  //print(error.toString());
                },
                onPageError: (page, error) {
                  setState(() {
                    errorMessage = '$page: ${error.toString()}';
                  });
                  //print('$page: ${error.toString()}');
                },
                onViewCreated: (AlhPdfViewController pdfViewController) {
                  _controller.complete(pdfViewController);
                },
                // onLinkHandler: (String? uri) {
                //   //print('goto uri: $uri');
                // },
                onPageChanged: (int? page, int? total) {
                  //print('page change: $page/$total');
                  setState(
                    () {
                      currentPage = page;
                    },
                  );
                },
              ),
      ),
      floatingActionButton: FutureBuilder<AlhPdfViewController>(
        future: _controller.future,
        builder: (context, AsyncSnapshot<AlhPdfViewController> snapshot) {
          if (snapshot.hasData) {
            return FloatingActionButton.extended(
              label: Row(
                children: [
                  IconButton(
                    icon: Icon(Icons.navigate_before,
                        color: (currentPage! > 0) ? Colors.white : Colors.grey),
                    onPressed: (currentPage! < pages!)
                        ? () async {
                            await snapshot.data!.setPage(page: currentPage! - 1);
                          }
                        : null,
                  ),
                  ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      elevation: 0,
                      side: const BorderSide(
                        color: Colors.white,
                      ),
                      minimumSize: Size.zero,
                      tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                    ),
                    onPressed: () async {
                      final result = await openDialog();
                      if (result == null || result.isEmpty) return;
                      int pageNumber = int.parse(result);
                      await snapshot.data!.setPage(page: pageNumber - 1);
                    },
                    child: Text("${currentPage! + 1}"),
                  ),
                  Text(" / $pages"),
                  IconButton(
                    icon: Icon(Icons.navigate_next,
                        color: (currentPage! + 1 < pages!)
                            ? Colors.white
                            : Colors.grey),
                    onPressed: (currentPage! < pages!)
                        ? () async {
                            await snapshot.data!.setPage(page: currentPage! + 1);
                          }
                        : null,
                  ),
                ],
              ),
              onPressed: null,
            );
          }
          return Container();
        },
      ),
    );
      }

      Future<String?> openDialog() => showDialog<String>(
        context: context,
        builder: (context) => StatefulBuilder(
          builder: (context, setState) {
            return AlertDialog(
              title: const Text('Go to page'),
              content: TextField(
                //autofocus: true,
                decoration: const InputDecoration(hintText: 'Page number'),
                keyboardType: TextInputType.number,
                inputFormatters: <TextInputFormatter>[
                  FilteringTextInputFormatter.digitsOnly
                ],
                controller: textController,
                onChanged: (value) {
                  if (value.isNotEmpty) {
                    int pageNumber = int.parse(value);
                    setState(() {
                      isButtonActive = pageNumber < pages!;
                    });
                  }
                },
                onSubmitted: (_) => gotToPage(),
              ),
              actions: [
                TextButton(
                  onPressed: () {
                    Navigator.of(context).pop();
                    
                  },
                  child: const Text('Cancel'),
                ),
                TextButton(
                  style: TextButton.styleFrom(
                      onSurface: Theme.of(context).primaryColor),
                  onPressed: isButtonActive
                      ? () {
                          gotToPage();
                          
                        }
                      : null,
                  child: const Text('Move'),
                ),
              ],
            );
          },
        ),
      );

      void gotToPage() {
        Navigator.of(context).pop(textController?.text);
        textController?.clear();
      }
    }

**Comment by andreBalh** [comment]
Hello @alexaung
Thank you for opening this issue. I take a look on your issue.

**Comment by andreBalh** [comment]
So if I am understanding your problem correctly @alexaung :
You expect that the current page of the PDF should change, if you update your `currentPage` value?
If that is the case, currently you cannot update the page by updating the parameter `defaultPage`. It is only possible with the controller. 
I could think about a solution that you don't have to set the value manually. Maybe changing the parameter `defaultPage` to `currentPage`. Then you could have two possibilities to update the page.

**Comment by alexaung** [comment]
@andreBalh Thank for reply. Actually, I don't change the defaultPage. I just call `await snapshot.data!.setPage(page: pageNumber - 1);` after I closed the dialog, see line number 4. If I don't call the dialog, it changed the page. Now I found one strange behavior that pdf view change the white screen when open the dialog. I don't even enter the page number yet. 

      `final result = await openDialog();
        if (result == null || result.isEmpty) return;
        int pageNumber = int.parse(result);
        await snapshot.data!.setPage(page: pageNumber - 1);`

P.S If I comment out first three line, don't open dialog, and set the number, `await snapshot.data!.setPage(page: 50);` I will go to page 50.

**Comment by alexaung** [comment]
I think you already implemented the navigation bar, first, prev, page info, next, last. There is only one thing need is go to page, page number entered by user. It is really need for user. otherwise, they need to click 50 time, if they want to go to page 50. Thanks you.

**Comment by alexaung** [comment]
I think something wrong with AlertDialog. If AlertDialog is open, parent widget, the PDFView is gone and change to blank screen. At that time I haven't  enter page number and submit yet. I think you better test with Alert Dialog.

**Comment by andreBalh** [comment]
Ok I think I know what causes this issue, it seems to have problems when the keyboard is showing up. 
This is definitely a bug. I will try to fix that, thank you for finding that @alexaung

**Comment by andreBalh** [comment]
I created a pull request #4 that should fix your issue

**Comment by andreBalh** [comment]
I released a new version `0.1.2`.
You can try that, if there are still problems, you can reopen this issue. @alexaung
