### ISSUE TITLE
Disabling scrollbar

### ISSUE THREAD

**Issue by mirkancal** [alhappler/alh_pdf_view#33]
Is it possible to disable the scrollbar on iOS? Documentation for `enableDefaultScrollHandle` says there's always scroll handle for iOS

**Comment by andreBalh** [comment]
Hello @mirkancal 
Thank you for opening the issue. This might be possible. I will look for that tomorrow and notify you

**Comment by andreBalh** [comment]
Hi @mirkancal 
I checked iOS and it's possible to hide the scrollbar. I will try to update the package today with this option. Later I also check that for Android.

**Comment by andreBalh** [comment]
I read your comment again and now I am not sure if that is what you wished for. Do you want to disable the scrolling permanently? @mirkancal

**Comment by mirkancal** [comment]
Hi @andreBalh, there's a scroll handle in the bottom, which seems to be managed by enableDefaultScrollHandle flag. But as you documented, disabling it doesn't work on iOS.

![gray_bar](https://user-images.githubusercontent.com/26160059/207030285-7a111967-3545-4487-9e0b-a138ee9dc71b.png)


I mean this tiny gray thing that moves randomly, looks like a scroll handle.

**Comment by andreBalh** [comment]
Ahh ok, that should be no problem @mirkancal

**Comment by andreBalh** [comment]
Just for your information, the fix should come tomorrow @mirkancal

**Comment by andreBalh** [comment]
Updated Version `1.2.0` is coming with `showScrollbar` as property for iOS. Default value is `true`, so you have to set it to `false`. @mirkancal
