### ISSUE TITLE
Feature: Add spacing between pages

### ISSUE THREAD

**Issue by SpirikleOfficial** [alhappler/alh_pdf_view#35]
Hi, I am not able to add spacing between the pdf pages and thus it seems congested. Please look into this. Thanks

**Comment by andreBalh** [comment]
Hello @SpirikleOfficial 
I checked if it is possible to add spacing between the pages.
For iOS, I can add `pageBreakMargins` that expects a spacing value for left, top, right and bottom.
For Android, I can add `spacing` that would add spacing between the pages.
That means that the behavior is a little bit different between iOS and Android. I will write a ticket in my company and try to release this feature in the next weeks, I hope that is ok for you.

**Comment by SpirikleOfficial** [comment]
Hi @andreBalh,
Thank you for your consideration. Has the option for adding spacing implemented?

**Comment by andreBalh** [comment]
Unfortunately not yet, should come hopefully in the next few weeks, sorry for this delay @SpirikleOfficial

**Comment by andreBalh** [comment]
I added this feature for iOS and Android @SpirikleOfficial 
I will release this today with version `1.3.0`
