### ISSUE TITLE
PDF View does not refresh

### ISSUE THREAD

**Issue by SpirikleOfficial** [alhappler/alh_pdf_view#41]
I am using AlhPdfView to show a pdf on a particular file path. I also have an edit button which goes to another screen where editing can be done. When returning to the previous screen, the AlhPdfView does not refresh accordingly to the changes made to the file on the path specified. Can you please see that a callback could be provided to refresh the pdf when changes are made? Or is there a way already?

**Comment by andreBalh** [comment]
Hmm I thought this should already work, but I will check that @SpirikleOfficial

**Comment by andreBalh** [comment]
So looking at the code, I guess it won't work currently. What you could do is to add a key to `AlhPdfView` that is related to your updated file, then it will be reloaded. @SpirikleOfficial

**Comment by SpirikleOfficial** [comment]
Ok, I will try. But will this be included in the future versions? Asking because using this package in multiple production apps.

**Comment by andreBalh** [comment]
I will add this to the future features because this is a feature which should work @SpirikleOfficial

**Comment by andreBalh** [comment]
I added this feature to our next sprint, so hopefully it will be implemented in the next weeks @SpirikleOfficial
