### ISSUE TITLE
Dependecy issues

### ISSUE THREAD

**Issue by Ayushpanditmoto** [alhappler/alh_pdf_view#43]
My App Screenshot build.gradle
![Screenshot_6](https://github.com/alhappler/alh_pdf_view/assets/31253617/2ccc9dfa-d0c6-4278-bddd-a194cfed6de0)
![Screenshot_4](https://github.com/alhappler/alh_pdf_view/assets/31253617/5869e826-c89a-47af-a830-ed2986b8d77e)
![Screenshot_5](https://github.com/alhappler/alh_pdf_view/assets/31253617/799eb7bf-6916-49bf-bb62-2f14c15bd1d7)

How to solve this issues

**Comment by andreBalh** [comment]
Hello I will check this. Did you try if you can start the example app of this package? @Ayushpanditmoto

**Comment by Ayushpanditmoto** [comment]
@andreBalh previously it is working i just upgraded my flutter to latest sdk after that i am facing this issues , create a new flutter latest version project and add that package and can you check whether its working or not if not please can you resolves this issues 😓

**Comment by andreBalh** [comment]
I will try it. Just to be sure, did you try `flutter clean` and then rebuilt the project? Sometimes there are issues after upgrading and can be resolved with clean. @Ayushpanditmoto

**Comment by andreBalh** [comment]
On which device did you built it? And which Android version does it have? @Ayushpanditmoto

**Comment by Ayushpanditmoto** [comment]
@andreBalh poco f4 android 13

**Comment by andreBalh** [comment]
I can reproduce your issue. I will fix this asap. @Ayushpanditmoto

**Comment by andreBalh** [comment]
Updated package to version `1.4.0`, this fixes your issue :) @Ayushpanditmoto
