### ISSUE TITLE
Feature: Add "onTap"

### ISSUE THREAD

**Issue by mirkancal** [alhappler/alh_pdf_view#45]
Hi, I see there's gestureRecognizer, I want to call setState in my parent widget to hide some UI elements that I put around pdf viewer. So far I came up with this but didn't work.

```dart
AlhPdfView(
   gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>{
      Factory<OneSequenceGestureRecognizer>(
         () => TapGestureRecognizer()
            ..onTap = () {
              setState(() {
                hideUI = !hideUI;
              });
             },
         ),
},
```

**Comment by andreBalh** [comment]
Hello @mirkancal 
So you need a callback when tapping on `AlhPdfView`?

**Comment by mirkancal** [comment]
hi @andreBalh, yes. I have few UI elements in the page like appbar and tabbar. I want to disable them with a flag when people tap on the pdf view.

**Comment by andreBalh** [comment]
Sorry for the delay again. I checked a little bit more and I think I have to implement a native solution. There is already the PR #36 for Android that adds an onTap. I will try to implement the same for iOS. I will add this ticket to our board and hopefully I can resolve this soon @mirkancal

**Comment by andreBalh** [comment]
Releasing this feature for Android and iOS with version `2.1.0` @mirkancal
