### ISSUE TITLE
Gradle plugin upgrade

### ISSUE THREAD

**Issue by E2-Harish** [alhappler/alh_pdf_view#50]
Can you upgrade the gradle plugin used in this package?
I am getting this warning when building with this package included

```
We recommend using a newer Android Gradle plugin to use compileSdk = 33

This Android Gradle plugin (7.1.3) was tested up to compileSdk = 32

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=33
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 33
Affected Modules: alh_pdf_view
```

**Comment by andreBalh** [comment]
Hello @E2-Harish 

Which version of this package are you using? 
The current compileSdk is specified to `34`.
Probably you need to update the version or run `flutter upgrade`.

And can you send me what you get from `flutter doctor -v`?

**Comment by E2-Harish** [comment]
Thanks after upgrading it works
